# Generated by Django 3.2.6 on 2022-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_remove_documento_criterio'),
        ('criterios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='documento',
            field=models.ManyToManyField(blank=True, null=True, to='documentos.Documento'),
        ),
    ]
