# Generated by Django 3.2.6 on 2022-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterios', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='criterio',
            field=models.ManyToManyField(blank=True, null=True, to='criterios.Criterio'),
        ),
    ]
