# Generated by Django 3.2.6 on 2022-10-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_criterio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='criterio',
        ),
    ]
