# Generated by Django 3.2.6 on 2022-10-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('saldo', models.FloatField()),
                ('cuentaBancaria', models.FloatField()),
            ],
        ),
    ]
